# Generated by Django 4.2.7 on 2023-11-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_authors_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='auther',
            new_name='author',
        ),
    ]
