# Generated by Django 4.2.7 on 2023-11-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_books_app', '0002_rename_email_user_email_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='my_book',
            new_name='my_user',
        ),
    ]
